let product = [
    {
        id: 1,
        title: "Maths",
        location: "Dubai",
        price: 250,
        image: "images/maths.jpg",
        availableSpace: 5,
        seats:5,
    },
    {
        id: 2,
        title: "English",
        location: "London",
        price: 100,
        image: "images/english.jpg",
        availableSpace: 5,
        seats:5,
    },
    {
        id: 3,
        title: "Chemistry",
        location: "Mauritius",
        price: 400,
        image: "images/chem.jpg",
        availableSpace: 5,
        seats:5,
    },
    {
        id: 4,
        title: "Biology",
        location: "Mauritius",
        price: 200,
        image: "images/bio.jpg",
        availableSpace: 5,
        seats:5,
    },
    {
        id: 5,
        title: "Physics",
        location: "Dubai",
        price: 500,
        image: "images/physics.jpg",
        availableSpace: 5,
        seats:5,
    },
    {
        id: 6,
        title: "Music",
        location: "Malta",
        price: 150,
        image: "images/music.jpg",
        availableSpace: 5,
        seats:5,
    },
    {
        id: 7,
        title: "Information Technology",
        location: "Malta",
        price: 500,
        image: "images/IT.jpg",
        availableSpace: 5,
        seats:5,
    },
    {
        id: 8,
        title: "Physical Education",
        location: "Malta",
        price: 250,
        image: "images/PE.jpg",
        availableSpace: 5,
        seats:5,
    },
    {
        id: 9,
        title: "Art",
        location: "Malta",
        price: 150,
        image: "images/art.jpg",
        availableSpace: 5,
        seats:5,
    },
    {
        id: 10,
        title: "Social Studies",
        location: "Malta",
        price: 100,
        image: "images/social.jpg",
        availableSpace: 5,
        seats:5,
    },
];